spring.application.name=clean-architecture-training

# ===== RabbitMQ Ayarları =====
# Docker'da çalışan RabbitMQ'ya bağlanmak için
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===== H2 Console (Debug için) =====
spring.h2.console.enabled=true
